version: '3.9'
services:
  db:
    image: postgres
    ports:
      - '5433:5432'
    volumes:
      - my-full-stack-app-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/data

volumes:
  my-full-stack-app-db:
